DROP DATABASE IF EXISTS groceries_db;
CREATE DATABASE groceries_db;
USE groceries_db;

CREATE TABLE groceries
(
    id INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (id),
    name VARCHAR(200) UNIQUE NOT NULL,
    quantity VARCHAR(200) NOT NULL,
    category VARCHAR (200) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);